### ISSUE TITLE
How to sign offline?

### ISSUE THREAD

**Issue by MaoxinCao** [ProChain/SwiftyEOS#15]

**Comment by croath** [comment]
Hi @MaoxinCao , did you mean signing transaction? All transactions are signed offline with SwiftyEOS. Try to make a token transfer like the README file described: Using `Currency.transferCurrency`.

But some params are needed to be fetched from an eos endpoint (block prefix and/or block number).

**Comment by croath** [comment]
Hi @MaoxinCao , did you solve the problem?

**Comment by zhenghongchuan** [comment]
I have the same question..

**Comment by croath** [comment]
@zhenghongchuan it's a signed transaction, right?

I'll make it clear by posting an example. I have a transaction to make, it's a token-transfer transaction:

1. Account `agoodaccount` wants to transfer 1 EOS to account `gq3dinztgage`. The first step is to have a transaction action like this:

```json
{  
         "account":"eosio.token",
         "name":"transfer",
         "authorization":[  
            {  
               "actor":"agoodaccount",
               "permission":"active"
            }
         ],
         "data":{  
            "from":"agoodaccount",
            "to":"gq3dinztgage",
            "quantity":"1.0000 EOS"
         }
      }
```

2. With the raw transaction action, the next step is to pack it, by convert this key-value based structure(json) to hex representation with the contract's ABI. After packing, the whole trasaction will be something like you've posted:

`a4f38c5b390282247889000000000100a6823403ea3055000000572d3ccdcd01104260d33d364dc300000000a8ed323241104260d33d364dc3204260d33d364dc31027000000000000044a554e474c45002054657374206279207368616e676a696e67202e2020323031383039303330303200`

(It's the string I just copied from your code.

3. After that, the final thing is signing. Using EOS's standard signing method, and your private key, to sign this hex string to a signature:

`SIG_K1_KdRNkKSDNFUb7gU45UZcySykeGRGp4ESzEZj4pyJwWsuDVkRcHjREViyF1qQmci8981zib3zGebD64YAXgsNQkzAa7jftK` 

4. Then we got the result:

```json
{
  "signatures": [
    "SIG_K1_KdRNkKSDNFUb7gU45UZcySykeGRGp4ESzEZj4pyJwWsuDVkRcHjREViyF1qQmci8981zib3zGebD64YAXgsNQkzAa7jftK"
  ],
  "compression": "none",
  "packed_context_free_data": "",
  "packed_trx": "a4f38c5b390282247889000000000100a6823403ea3055000000572d3ccdcd01104260d33d364dc300000000a8ed323241104260d33d364dc3204260d33d364dc31027000000000000044a554e474c45002054657374206279207368616e676a696e67202e2020323031383039303330303200"
}
```

The packed transaction, signature, no compression by default, and no context free data. It's ready. Then we can ship this `signed transaction` http body to one of the EOS RPC endpoint using RPC `push_transaction` API:

`POST http://yourdomainandport/v1/chain/push_transaction`

That's all.

With SwiftyEOS, it's much easier to make it happen because you don't need to care about the step 2 and step 3:

```swift
var transfer = Transfer()
transfer.from = "agoodaccount"
transfer.to = "gq3dinztgage"
transfer.quantity = "1.0000 EOS"
transfer.memo = "eureka"

Currency.transferCurrency(transfer: transfer, privateKey: importedPk!, completion: { (result, error) in
    if error != nil {
        if error is RPCErrorResponse {
            print("\((error as! RPCErrorResponse).errorDescription())")
        } else {
            print("other error: \(String(describing: error?.localizedDescription))")
        }
    } else {
        print("done.")
    }
})
```

You can also find the code snippet in the project readme file. It's written in Swift but could be used with Objective-C, too.

**Comment by MaoxinCao** [comment]
@croath Thanks Reply.

I am currently doing is multi-signature, so I need to sign offline on multiple terminals. But the signature in SwiftyEOS seems to be put into the transaction.

**Comment by croath** [comment]
@MaoxinCao Sorry that multi-sig is not supported yet.

But I'm sure I could provide a low-level method just for calculating signatures for a given context. Will be ready in next versions.

**Comment by croath** [comment]
@zhenghongchuan With `currentAccount` there's no need to take the privateKey, just use `SELocalAccount`'s `pushTransaction`. Unlock with a password is a safer way in iOS.

**Comment by zhenghongchuan** [comment]
@croath The point is that can I get the sign json by my currentAccount, and how to do it. And can I create wallet by a account? Thanks.

**Comment by croath** [comment]
@zhenghongchuan 

1. Yes and no. There's way you can get the final signed json yourself, read the source file and find the way I do in Transaction.swift.

2. No. A wallet can not be created by just a name. A private key associated with that account is needed.

**Comment by croath** [comment]
@MaoxinCao Then what the `error` is?

And are you sure the code you wanna use is `currency`?

**Comment by zhenghongchuan** [comment]
@croath Thank you!

**Comment by MaoxinCao** [comment]
@croath I fix it. 

```
let abi = try AbiJson(code: "eosio.token", action: "transfer", json: jsonString)
```

**Comment by croath** [comment]
🎉
